version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"    # Public HTTP
      - "${HTTPS_PORT}:443"  # Public HTTPS
      - "${ADMIN_PORT}:81"   # Admin Web UI
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # DB_SQLITE_FILE=/data/database.sqlite   # optional
      # DISABLE_IPV6=true                      # optional
    volumes:
      - ${DOCKERCONFDIR}/nginx-proxy-manager/data:/data
      - ${DOCKERCONFDIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - synobridge

networks:
  synobridge:
    external: true
