title: IT & Homelab Portfolio
description: Real-world DevOps/sysadmin projects
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

github_username: TDNinfra
permalink: pretty

markdown: kramdown
url: https://tdninfra.github.io
baseurl: /homelab-portfolio
