version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true          # remove old images after update
      - WATCHTOWER_INCLUDE_STOPPED=true  # update even stopped containers
      - WATCHTOWER_REVIVE_STOPPED=false  # don't restart stopped containers
      - WATCHTOWER_SCHEDULE=0 0 2 * * *  # cron: daily at 02:00
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
