version: "3.8"
networks:
  recyclarr:
    name: recyclarr
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKERCONFDIR}/recyclarr:/config
    environment:
      - TZ=${TZ}
    networks:
      - recyclarr
    restart: unless-stopped
