version: "3.8"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/sabnzbd/config:/config
      - ${DOCKERSTORAGEDIR}/usenet/complete:/downloads
      - ${DOCKERSTORAGEDIR}/usenet/incomplete:/incomplete
      - ${DOCKERSTORAGEDIR}/usenet:/nzbs
    ports:
      - "${HTTP_PORT}:8080"
    restart: unless-stopped
